### ISSUE TITLE
Expansion and collapsing all section when click on outer tableview button

### ISSUE THREAD

**Issue by nileshordex** [fuzz-productions/FZAccordionTableView#35]
I want to new functionality add for Tableview all section expand when click on outer tableview button and again click then collapse all section. I need to these functionality any one help me.

**Comment by kgaidis** [comment]
@nileshordex 

The following should work:
https://github.com/fuzz-productions/FZAccordionTableView/issues/34#issuecomment-292397445

**Comment by nileshordex** [comment]
Thank you so much kgaidis, #34 bug no is help full.

**Comment by nileshordex** [comment]
@kgaidis 
I using #34 (comment) but Tableview is super slow reload when using this code i need to faster collapse and expand tableview cell so give me solution please.

**Comment by kgaidis** [comment]
I'm not sure what you mean by faster. Maybe you could show a video and also post your code so I could understand the problem better.

**Comment by nileshordex** [comment]
I attached video Link for facing issue.
1). https://www.dropbox.com/s/zft64desyzrbunl/tableview.mp4?dl=0

This video show in I click on view full menu and few second to waiting for all section expand and collapse.
My code :
```
- (void)BtnFullMenuTapped:(id)sender
{
    if(BtnFullMenu.tag == 0){
        BtnFullMenu.tag = 1;
        for (int i=0; i<[arrItemGrp count]; i++) 
        {
            [self.tableRestDetail closeAllSectionsExcept:i];
            [self.tableRestDetail beginUpdates];
            [self.tableRestDetail endUpdates];
        }
        
        for (int i=0; i<[arrItemGrp count]; i++) {
            [self.tableRestDetail isSectionOpen:i];
            [self.tableRestDetail toggleSection:i];
            [self.tableRestDetail beginUpdates];
            [self.tableRestDetail endUpdates];
        }
        
        LblViewFullMenu.textColor = [UIColor colorWithRed:239.0/255.0 green:62.0/255.0 blue:51.0/255.0 alpha:1.0 ];
        [ImgArrow1 setImage:[UIImage imageNamed:@"up.png"] forState:UIControlStateNormal];
        [ImgArrow2 setImage:[UIImage imageNamed:@"up.png"] forState:UIControlStateNormal];
        
    }else{
        BtnFullMenu.tag = 0;
        for (int i=0; i<[arrItemGrp count]; i++) {
            [self.tableRestDetail closeAllSectionsExcept:i];
            [self.tableRestDetail beginUpdates];
            [self.tableRestDetail endUpdates];
        }
        LblViewFullMenu.textColor = [UIColor whiteColor];
        [ImgArrow1 setImage:[UIImage imageNamed:@"down.png"] forState:UIControlStateNormal];
        [ImgArrow2 setImage:[UIImage imageNamed:@"down.png"] forState:UIControlStateNormal];
    }
}
```

**Comment by kgaidis** [comment]
Thank you for the video and code!

I would try the following because I think the loop is doing unnecessary work by calling `closeAllSectionsExcept`. I would also avoid relying on `closeAllSectionsExcept` because it seems like an internal method and it could just disappear in future versions. 

```
- (void)openAllSections {
	[self.tableView beginUpdates];
	// iterate all sections
	for (NSInteger i = 0; i < self.tableView.numberOfSections; i++) {
		// if section is not open, toggle it (making it open)
		if (![self.tableView isSectionOpen:i]) {
			[self.tableView toggleSection:i];
		}
	}
	[self.tableView endUpdates];
}
```

If that doesn't make it better, how many rows and sections are there in total in the largest table view? There is a chance that there are just so many rows in each section that looping through all of them is just going to take too long no matter what. In those cases, there might need to be some special methods created to handle quickly opening all sections. That would require updates to the library and maybe coming up with some novel solutions. 

However, usually in these cases I would recommend to use Instruments tool to profile which parts of the code are taking the longest. There is a chance that the problem could be unrelated to FZAccordionTableView, I have no way of knowing this unless I try to replicate this scenario with the number of rows you are using in an isolated example.

**Comment by nileshordex** [comment]
Thanks for committed and great reply Me!
Tableview In N... No of section or N... No of row in tableview is a dynamic section and row create. When you update the library then comment me It a very urgent for me.

**Comment by nileshordex** [comment]
🥇

**Comment by kgaidis** [comment]
@nileshordex 

Did the code I posted improve the speed? And if not, how many rows and sections in total do you have?

**Comment by nileshordex** [comment]
@kgaidis 
I using your posted code. when I close all section at that time all section close but first section isnot close.

**Comment by kgaidis** [comment]
@nileshordex 

The code I posted was for opening all the sections, to close the sections you have to reverse the boolean statement:

```
- (void)closeAllSections {
	[self.tableView beginUpdates];
	// iterate all sections
	for (NSInteger i = 0; i < self.tableView.numberOfSections; i++) {
		// if section is open, toggle it (making it closed)
		if ([self.tableView isSectionOpen:i]) {
			[self.tableView toggleSection:i];
		}
	}
	[self.tableView endUpdates];
}
```

You also want to make sure that `allowMultipleSectionsOpen = YES` and `keepOneSectionOpen = NO`.

I tested my code in an example and it worked fine.
