### ISSUE TITLE
Header Image not changing properly on tableview scroll

### ISSUE THREAD

**Issue by yaalisri** [fuzz-productions/FZAccordionTableView#45]
I have an uparrow and downarrow image to show in the header. When i open a section, up arrow is correctly getting changed, but when i scroll the tableview i can see the second section image is also getting changed any without selection. How to fix this?

**Comment by kgaidis** [comment]
Hi @yaalisri 

Potential bugs aside, it sounds like you may have some header reuse issue? Could post some code of how you achieve your current behavior? Otherwise, I'm just guessing. 

Make sure that when you creating the header, you correctly set the images for the correct "header state," which is either `open` or `closed`. This would be in the `func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? `

This can be found by utilizing: `- (BOOL)isSectionOpen:(NSInteger)section;`. If the section is open, use the up arrow, if its closed, use the down arrow.
