### ISSUE TITLE
Tap on headerView is not working

### ISSUE THREAD

**Issue by DivyaSaraswati** [fuzz-productions/FZAccordionTableView#52]
Some times Touch on header view is not recognised. and it is mostly occurring when your header view is released from memory. 
Steps to Reproduce
1. First reload the tableview
2. All section were closed for the first time
3. Then try to scroll up until top 3 headers disappears and then release the scroll 
4. then tap on header view.
5. no action will be received.  

I guess there is problem with tap gesture delegate.

**Comment by kgaidis** [comment]
Hi, apologize for no reply for a very long time! Thank you for the replication steps. 

I tried to replicate this using the example project and I could not. 

If you wish me to find a fix for this, I would post the code and possibly a video of you replicating this issue **using the example project**. It is often very difficult to replicate issues that others are having because they can be using `UITableView` in an infinite number of ways - it is a very flexible class. However, if it can be shown in a closed environment, I can replicate it and then find a fix. The nice thing is that the example project is very simple, so it's very easy to modify. 

Until that happens, I will close this.
