### ISSUE TITLE
Expansion and collapsing with transparent section headers

### ISSUE THREAD

**Issue by borut-t** [fuzz-productions/FZAccordionTableView#7]
I've modified your example header view background and add transparency to it. Please take a look at the screenshot bellow.

![bdfb8158-0246-11e6-98a1-f014f3950128](https://cloud.githubusercontent.com/assets/677166/14526961/10009f6a-0247-11e6-9f36-1376236ca939.png)

Cells goes bellow section headers and there for you see such an ugly result.

**Comment by kgaidis** [comment]
So this is tricky because the premise of this library is that it works seamlessly with `UITableView`. That, part, means that `FZAccordionTableView` is just a library that makes clever use of `UITableView` methods. That also, part, means that it's at the mercy of what `UITableView` does, and this is just how it's default animations work.

The solution to this would be more about how to hack around this, rather than, how do we rewrite the animations because "we don't control" what `UITableView` does. 

One solution is to just fade cells to mitigate this effect. Would this option make it into the library? Maybe, I'm actually surprised that it works pretty well, but it's modifying the contentView of the cell which might be a surprising side-effect to a user of the library. Although, as an opt-in option, this could be a reasonable negative.

Here's the code to insert in .m file:

``` objc
- (void)deleteRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation
{
    [UIView animateWithDuration:[CATransaction animationDuration] animations:^{
        for (NSIndexPath *indexPath in indexPaths) {
            UITableViewCell *cell = [self cellForRowAtIndexPath:indexPath];
            cell.contentView.alpha = 0.0;
        }
    }];
    [super deleteRowsAtIndexPaths:indexPaths withRowAnimation:animation];
}

- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath
{
    if (cell.contentView.alpha != 1.0) {
        [UIView animateWithDuration:[CATransaction animationDuration] animations:^{
            cell.contentView.alpha = 1.0;
        }];
    }
}
```

**Comment by borut-t** [comment]
Unfortunately this does not solve the problem. Cells still overlaps section headers.
